### ISSUE TITLE
Cannot find discordeco.js module..

### ISSUE THREAD

**Issue by SiddharthGautam1** [SharifPoetra/tokisaki#14]
Please help me.. When I do **node index.js** it says cannot find module **discordeco.js**.. **Please help me.**.

**Comment by Vins2106** [comment]
> Please help me.. When I do **node index.js** it says cannot find module **discordeco.js**.. **Please help me.**.

delete `"discordeco.js": "0.5.0",` on package.json, and try to node index.js again
